"""Writes data/jobs.js into either the Hub repo (prod) or a local test file."""
from __future__ import annotations
import json
import logging
import os
import re
import subprocess
from datetime import datetime
from pathlib import Path

log = logging.getLogger(__name__)

# Field order for nicer git diffs — fields not listed go at the end alphabetically.
FIELD_ORDER = [
    "date", "edu_level", "submitted", "url", "title", "employer", "location",
    "edu_label", "salary", "source", "tip_resume", "tip_cover",
    "client_subject", "client_body", "region", "category", "company_url",
    "transit_accessible", "transit_agency", "transit_agency_url",
]


def write(jobs: list[dict], *,
          hub_repo_path: str | None = None,
          dry_run: bool = True,
          local_dir: Path | str | None = None,
          window_days: int = 14,
          do_git_push: bool = False) -> Path:
    """Write the data/jobs.js file. Returns the path written."""
    hub_repo_path = hub_repo_path or os.getenv("HUB_REPO_PATH", "").strip()
    local_dir = Path(local_dir) if local_dir else Path(__file__).resolve().parent.parent / "data"
    local_dir.mkdir(parents=True, exist_ok=True)

    if dry_run or not hub_repo_path:
        out_path = local_dir / "jobs-test.js"
    else:
        # Site is served from /docs (GitHub Pages); the job board reads docs/data/jobs.js.
        hub_data = Path(hub_repo_path) / "docs" / "data"
        hub_data.mkdir(parents=True, exist_ok=True)
        out_path = hub_data / "jobs.js"

    content = _render_js(jobs, window_days=window_days)
    out_path.write_text(content, encoding="utf-8")
    log.info("Wrote %d jobs to %s", len(jobs), out_path)

    if not dry_run and hub_repo_path:
        _bump_cache_token(Path(hub_repo_path))

    if not dry_run and do_git_push and hub_repo_path:
        _git_push(Path(hub_repo_path))

    return out_path


def _bump_cache_token(repo_path: Path) -> None:
    """Bump the ?v= cache-bust token on jobs.js in docs/jobs.html to today's date.

    Browsers cache jobs.js by its full URL (query string included), so without this
    returning visitors keep their old copy until the token changes. Touches only the
    jobs.js tag, never site.js or any other asset.
    """
    today = datetime.now().strftime("%Y%m%d")
    html_path = repo_path / "docs" / "jobs.html"
    if not html_path.exists():
        log.warning("jobs.html not found at %s — skipping cache-token bump", html_path)
        return
    html = html_path.read_text(encoding="utf-8")
    new_html, n = re.subn(r'(data/jobs\.js\?v=)[^"\']*', r"\g<1>" + today, html)
    if n == 0:
        log.warning("No data/jobs.js?v= token found in jobs.html — skipping bump")
        return
    if new_html != html:
        html_path.write_text(new_html, encoding="utf-8")
        log.info("Bumped jobs.js cache token to v=%s in %s", today, html_path)


def _render_js(jobs: list[dict], window_days: int = 14) -> str:
    """Render jobs as a JS file matching the Hub's expected format."""
    today = datetime.now().strftime("%Y-%m-%d")
    meta = {"generated": today, "regions": 5, "window_days": window_days}
    cleaned = [_clean_for_output(j) for j in jobs]

    header = (
        f"// Generated by weekly-job-report-pipeline on {today}\n"
        f"// Total jobs: {len(cleaned)}\n"
    )
    meta_line = "window.HUB_JOBS_META = " + json.dumps(meta) + ";\n"
    jobs_line = "window.HUB_JOBS = " + json.dumps(cleaned, ensure_ascii=False, indent=2) + ";\n"
    return header + meta_line + jobs_line


def _clean_for_output(j: dict) -> dict:
    """Strip None fields and reorder for consistent output."""
    keep = {k: v for k, v in j.items() if v is not None and k != "description"}
    ordered: dict = {}
    for k in FIELD_ORDER:
        if k in keep:
            ordered[k] = keep.pop(k)
    # Append any unexpected fields
    for k in sorted(keep.keys()):
        ordered[k] = keep[k]
    return ordered


def _git_push(repo_path: Path) -> None:
    """Run git add + commit + push in the Hub repo."""
    today = datetime.now().strftime("%Y-%m-%d")
    msg = f"Update weekly job listings ({today})"
    try:
        # Pull first so a clone left behind origin (e.g. site edits pushed elsewhere)
        # doesn't make the push a rejected non-fast-forward — keeps the weekly run self-healing.
        subprocess.run(["git", "-C", str(repo_path), "pull", "--rebase"], capture_output=True, text=True)
        subprocess.run(["git", "-C", str(repo_path), "add", "docs/data/jobs.js", "docs/jobs.html"], check=True)
        # Allow empty commit to be skipped gracefully
        result = subprocess.run(
            ["git", "-C", str(repo_path), "commit", "-m", msg],
            capture_output=True, text=True,
        )
        if result.returncode != 0 and "nothing to commit" in (result.stdout + result.stderr).lower():
            log.info("No changes to commit.")
            return
        if result.returncode != 0:
            log.warning("git commit failed: %s %s", result.stdout, result.stderr)
            return
        subprocess.run(["git", "-C", str(repo_path), "push"], check=True)
        log.info("Pushed update to GitHub.")
    except subprocess.CalledProcessError as e:
        log.error("git operation failed: %s", e)
